// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg5xAjUu29JJ02TJ4CspaPxCi71bDGDCk',
    appId: '1:112719003472:web:77d5bc89704eb7ad7ef655',
    messagingSenderId: '112719003472',
    projectId: 'svttraining-a5400',
    authDomain: 'svttraining-a5400.firebaseapp.com',
    storageBucket: 'svttraining-a5400.appspot.com',
    measurementId: 'G-TCJP72D9H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqKBKZYQC5lLiURTNz5-k6BAlY4XkWg1M',
    appId: '1:112719003472:android:963e110176d7e5bc7ef655',
    messagingSenderId: '112719003472',
    projectId: 'svttraining-a5400',
    storageBucket: 'svttraining-a5400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0kBfgbqln2e9XW5WvIUQdCVAwKHaaZ64',
    appId: '1:112719003472:ios:f61c11dcbd2614177ef655',
    messagingSenderId: '112719003472',
    projectId: 'svttraining-a5400',
    storageBucket: 'svttraining-a5400.appspot.com',
    androidClientId: '112719003472-56226gat7u5dh4kv0qcbme5h7cf935ub.apps.googleusercontent.com',
    iosClientId: '112719003472-mn4nntp4nnj2s0o3aiah73kvobk5tkvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0kBfgbqln2e9XW5WvIUQdCVAwKHaaZ64',
    appId: '1:112719003472:ios:f61c11dcbd2614177ef655',
    messagingSenderId: '112719003472',
    projectId: 'svttraining-a5400',
    storageBucket: 'svttraining-a5400.appspot.com',
    androidClientId: '112719003472-56226gat7u5dh4kv0qcbme5h7cf935ub.apps.googleusercontent.com',
    iosClientId: '112719003472-mn4nntp4nnj2s0o3aiah73kvobk5tkvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing2',
  );
}
